main/apps/loginreg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='loginIndex'),
    url(r'^process/create$', views.create, name='loginCreate'),
    url(r'^process/login$', views.login, name='loginLogin'),
    url(r'^success$', views.success, name='loginSuccess'),
    url(r'^logout$', views.signOut, name='signOut')
]

main/main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.loginreg.urls', namespace='login')),
    url(r'^travels/', include('apps.travels.urls', namespace='travels')),
]

main/apps/loginreg/models.py
from django.db import models
import re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
#UserManager
class UserManager(models.Manager):
    def register(self, postData):
        #declare empty dictionary to hold errors
        errorList = {
            'errorsPresent': False,
            'emailErrors': [],
            'fnameErrors': [],
            'lnameErrors': [],
            'pwordErrors': [],
            'confpwErrors': [],
            'emailInDb': [],
        }
        #check if user attempted to submit any blanks or less than required length
        if len(postData['email']) == 0:
            errorList['emailErrors'].append("Email cannot be blank!")
            errorList['errorsPresent'] = True
        if len(postData['fname']) < 3:
            errorList['fnameErrors'].append("First name must be at least 3 characters!")
            errorList['errorsPresent'] = True
        if len(postData['lname']) < 3:
            errorList['lnameErrors'].append("Last name must be at least 3 characters!")
            errorList['errorsPresent'] = True
        if len(postData['pword']) < 8:
            errorList['pwordErrors'].append("Password must be at least 8 characters!")
            errorList['errorsPresent'] = True

        #vcheck if email exists in database and catch DoesNotExist error if it doesnt
        try:
            preExist = self.get(email = postData['email'])
        except self.model.DoesNotExist:
            preExist = False

        #if entry exists, preExist will not be false, append error, else continue validations for email
        if preExist is False:
            #check if first name is alpha
            if not postData['fname'].isalpha():
                errorList['fnameErrors'].append("First name must be all letters!")
                errorList['errorsPresent'] = True
            if not postData['lname'].isalpha():
                errorList['lnameErrors'].append("Last name must be all letters!")
                errorList['errorsPresent'] = True
            if not EMAIL_REGEX.match(postData['email']):
                errorList['emailErrors'].append("Email improperly formatted!")
                errorList['errorsPresent'] = True
            if not postData['pword'] == postData['confpw']:
                errorList['confpwErrors'].append("Passwords must match!!")
                errorList['errorsPresent'] = True
        else:
            errorList['emailInDb'].append("Email already in DB!")
            errorList['errorsPresent'] = True
            
        if errorList['errorsPresent']:
            return errorList    
        else:
            #create entry and return no errors
            self.create(first_name = postData['fname'], last_name = postData['lname'], email = postData['email'], password = postData['pword'])

            return errorList
    
    def login(self, postData):
        #declare empty dictionary to hold errors
        errorList = {
            'errorsPresentLogin': False,
            'emailLoginErrors': [],
            'pwordLoginErrors': [],
        }

        #check if email or password is empty
        if len(postData['email_login']) == 0:
            errorList['emailLoginErrors'].append("Email can't be blank!")
            errorList['errorsPresentLogin'] = True
        if len(postData['pword_login']) == 0:
            errorList['pwordLoginErrors'].append("Password can't be blank!")
            errorList['errorsPresentLogin'] = True

        #check if errors are present
        if errorList['errorsPresentLogin']:
            return errorList
        
        #compare email against db capture doesnotexist error
        try:
            preExist = self.get(email = postData['email_login'])
        except self.model.DoesNotExist:
            errorList['emailLoginErrors'].append("Email does not exist!")
            errorList['errorsPresentLogin'] = True
            return errorList

        if not postData['email_login'] == preExist.email:
            errorList.append("Sorry, email does not exist or match our database")
            errorList['errorsPresentLogin'] = True
        if not postData['pword_login'] == preExist.password:
            errorList['pwordLoginErrors'].append("Sorry, wrong password")
            errorList['errorsPresentLogin'] = True

        return errorList
# Create your models here.
class Users(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    #connect instance of UserManager
    objects = UserManager()

main/apps/loginreg/views.py
from django.shortcuts import render, HttpResponse, redirect
from apps.loginreg.models import Users
from django.core.urlresolvers import reverse

# Create your views here.
def index(request):
    if 'errors' not in request.session:
        request.session['errors'] = 0


    return render(request, 'loginreg/index.html')

def create(request):
    request.session['errors'] = Users.objects.register(request.POST)

    if request.session['errors']['errorsPresent'] is True:
        return redirect(reverse('login:loginIndex'))
    else:
        request.session['logged_user'] = request.POST['email']
        return redirect(reverse('login:loginSuccess'))

def login(request):
    request.session['errors'] = Users.objects.login(request.POST)


    if request.session['errors']['errorsPresentLogin'] is True:
        return redirect(reverse('login:loginIndex'))
    else:
        request.session['logged_user'] = request.POST['email_login']
        return redirect(reverse('login:loginSuccess'))

def success(request):

    return redirect(reverse('travels:travelsIndex'))

def signOut(request):
    request.session.clear()

    return redirect(reverse('login:loginIndex'))

main/apps/loginreg/templates/loginreg/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>Login & Reg | Home</title>
    <link rel='stylesheet' href=''>
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
    <script>
        $(document).ready(function() {
        });
    </script>
    <style>
        p {
            color: red;
        }

        fieldset {
            width: 20%;
            margin: 0px auto;
        }
    </style>
</head>
<body>
    <fieldset>
        <legend>Registration</legend>

        <form action='{% url "login:loginCreate" %}' method='post'>
            {% csrf_token %}
            {% for item in request.session.errors.fnameErrors %}
                <p>{{item}}</p>
            {% endfor %}
            <label for='fname'>First Name: </label>
            <input type='text' name='fname'>
            <hr>
            {% for item in request.session.errors.lnameErrors %}
                <p>{{item}}</p>
            {% endfor %}
            <label for='lname'>Last Name: </label>
            <input type='text' name='lname'>
            <hr>
            {% for item in request.session.errors.emailErrors %}
                <p>{{item}}</p>
            {% endfor %}
            <label for='email'>Email: </label>
            <input type='text' name='email'>
            <hr>
            {% for item in request.session.errors.pwordErrors %}
                <p>{{item}}</p>
            {% endfor %}
            <label for='pword'>Password: </label>
            <input type='password' name='pword'>
            <hr>
            {% for item in request.session.errors.confpwErrors %}
                <p>{{item}}</p>
            {% endfor %}
            <label for='confpw'>Confirm Password: </label>
            <input type='password' name='confpw'>
            <hr>
            <input type='submit' name='submit'>
        </form>
    </fieldset>
    <fieldset>
        <legend>Login</legend>
        <form action='{% url "login:loginLogin" %}' method='post'>
            {% csrf_token %}
            {% for item in request.session.errors.emailLoginErrors %}
                <p>{{item}}</p>
            {% endfor %}
            <label for='email_login'>Email: </label>
            <input type='text' name='email_login'>
            <hr>
            {% for item in request.session.errors.pwordLoginErrors %}
                <p>{{item}}</p>
            {% endfor %}
            <label for='pword_login'>Password: </label>
            <input type='password' name='pword_login'>
            <input type='submit' name='submit'>
        </form>
    </fieldset>
</body>
</html>

main/apps/loginreg/templates/loginreg/success.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title></title>
    <link rel='stylesheet' href=''>
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
    <script>
        $(document).ready(function() {
        });
    </script>
</head>
<body>
    <h1>I guess it kinda works</h1>
    <h1>You are {{request.session.logged_user}}</h1>
</body>
</html>