main/apps/loginreg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='loginIndex'),
    url(r'^process/create$', views.create, name='loginCreate'),
    url(r'^process/login$', views.login, name='loginLogin'),
    url(r'^success$', views.success, name='loginSuccess'),
    url(r'^logout$', views.signOut, name='signOut')
]

main/apps/travels/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='travelsIndex'),
    url(r'^add$', views.add, name='addTravels'),
    url(r'^create$', views.create, name='createTravel'),
    url(r'^destination/(?P<id>\d+)$', views.destinationView, name='destinationView'),
    url(r'^joinTrip/(?P<id>\d+)$', views.joinTrip, name='tripJoin')
]

main/main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.loginreg.urls', namespace='login')),
    url(r'^travels/', include('apps.travels.urls', namespace='travels')),
]

main/apps/travels/models.py
from django.db import models
from apps.loginreg.models import Users
import datetime

class TripsManager(models.Manager):
    def addTrip(self, postData, user):
        #declare empty dictionary to hold errors
        errorList = {
            'errorsPresent': False,
            'destinationErrors': [],
            'descriptionErrors': [],
            'startDateErrors': [],
            'endDateErrors': []
        }
        #check if user attempted to submit any blanks or less than required length
        if len(postData['destination']) == 0:
            errorList['destinationErrors'].append("Destination cannot be blank!")
            errorList['errorsPresent'] = True
        if len(postData['description']) == 0:
            errorList['descriptionErrors'].append("Description cannot be blank!")
            errorList['errorsPresent'] = True
        if len(postData['start_date']) == 0:
            errorList['startDateErrors'].append("Start date cannot be blank!")
            errorList['errorsPresent'] = True
        if len(postData['end_date']) == 0:
            errorList['endDateErrors'].append("End date cannot be blank!")
            errorList['errorsPresent'] = True

        #check if user is attempting to enter date before today and whether end date is prior to start date
        if postData['start_date'] < str(datetime.date.today()):
            errorList['startDateErrors'].append("Start date cannot be before today! What are you even doing?")
            errorList['errorsPresent'] = True
        if postData['end_date'] < str(datetime.date.today()):
            errorList['endDateErrors'].append("End Date cannot be before today!")
            errorList['errorsPresent'] = True
        if postData['end_date'] < postData['start_date']:
            errorList['endDateErrors'].append("End Date cannot be before start date!")
            errorList['errorsPresent'] = True


        if errorList['errorsPresent']:
            return errorList
        else:
            self.create(destination = postData['destination'], description = postData['description'], start_date = postData['start_date'], end_date = postData['end_date'], plannedby_user_id = user)
            return errorList

# Create your models here.
class Trips(models.Model):
    destination = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    start_date = models.DateField(auto_now=False)
    end_date = models.DateField(auto_now=False)
    plannedby_user = models.ForeignKey(Users, related_name='planner')
    user_joining = models.ManyToManyField(Users, related_name='joining')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = TripsManager()

main/apps/travels/views.py
from django.shortcuts import render, HttpResponse, redirect
from apps.loginreg.models import Users
from apps.travels.models import Trips
from django.core.urlresolvers import reverse
from django.db.models import Q

# Create your views here.
def index(request):
    if 'errors' not in request.session:
        request.session['errors'] = 0

    user = Users.objects.get(email=request.session['logged_user'])

    context = {
        'allTravels': Trips.objects.all().exclude(Q(plannedby_user=user.id) | Q(user_joining=user.id)),
        'userTravels': Trips.objects.filter(Q(plannedby_user=user.id) | Q(user_joining=user.id)),
        'users': Users.objects.all(),
    }

    return render(request, 'travels/index.html', context)

def add(request):

    return render(request, 'travels/add.html')

def create(request):
    user = Users.objects.get(email=request.session['logged_user'])

    request.session['errors'] = Trips.objects.addTrip(request.POST, user.id)

    if request.session['errors']['errorsPresent'] is True:
        return redirect(reverse('travels:addTravels'))
    else:
        return redirect(reverse('travels:travelsIndex'))

def destinationView(request, id):
    currentTrip = Trips.objects.get(id=id)
    context = {
        'currentTravel': Trips.objects.get(id=id),
        'planner': Users.objects.get(id=currentTrip.plannedby_user_id),
        'joiningUsers': currentTrip.user_joining.all()
    }

    return render(request, 'travels/view.html', context)

def joinTrip(request, id):
    user = Users.objects.get(email=request.session['logged_user'])
    trip = Trips.objects.get(id=id)

    trip.user_joining.add(user)

    return redirect(reverse('travels:travelsIndex'))

main/apps/travels/templates/travels/add.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>Add Destination</title>
    <link rel='stylesheet' href=''>
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
    <script>
        $(document).ready(function() {
        });
    </script>
    <style>
        .main {
            width: 20%;
            margin: 0px auto;

        }

        p {
            color: red;
        }
    </style>
</head>
<body>
    <div class='main'>
        <a href='{% url "travels:travelsIndex" %}'>Home</a>
        <a href='{% url "login:signOut" %}'>Logout</a>
        <fieldset>
            <legend>Add a Trip</legend>
            <form action='{% url "travels:createTravel" %}' method='post'>
                {% csrf_token %}
                {% for item in request.session.errors.destinationErrors %}
                    <p>{{item}}</p>
                {% endfor %}
                <label for='destination'>Destination</label>
                <input type='text' name='destination'>
                <hr>
                {% for item in request.session.errors.descriptionErrors %}
                    <p>{{item}}</p>
                {% endfor %}
                <label for='description'>Description</label>
                <input type='text' name='description'>
                <hr>
                {% for item in request.session.errors.startDateErrors %}
                    <p>{{item}}</p>
                {% endfor %}
                <label for='start_date'>Travel Start Date: | (YYYY-MM-DD)</label>
                <input type='text' name='start_date'>
                <hr>
                {% for item in request.session.errors.endDateErrors %}
                    <p>{{item}}</p>
                {% endfor %}
                <label for='end_date'>Travel End Date: | (YYYY-MM-DD)</label>
                <input type='text' name='end_date'>
                <br>
                <input type='submit' name='submit'>
            </form>
        </fieldset>
    </div>
</body>
</html>

main/apps/travels/templates/travels/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>Travels</title>
    <link rel='stylesheet' href=''>
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
    <script>
        $(document).ready(function() {
        });
    </script>
</head>
<body>
    <div class='wrapper'>
        <div class='header'>
            <h4>Welcome, {{request.session.logged_user}}!</h4>
            <a href='{% url "travels:addTravels" %}'>Add travel plan</a>
            <a href='{% url "login:signOut" %}'>Logout</a>
        </div>
        <div class='travels'>
            <fieldset>
                <legend>Your Upcoming Trips</legend>
                <table>
                    <thead>
                        <th>Destination</th>
                        <th>Travel Start Date</th>
                        <th>Travel End Date</th>
                        <th>Plan/Description</th>
                    </thead>
                    <tbody>
                        {% for item in userTravels %}
                        <tr>
                            <td><a href='{% url "travels:destinationView" id=item.id %}'>{{item.destination}}</td>
                            <td>{{item.start_date}}</td>
                            <td>{{item.end_date}}</td>
                            <td>{{item.description}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </fieldset>
            <!-- -->
            <fieldset>
                <legend>All Trips</legend>
                <table>
                    <thead>
                        <th>Planned by</th>
                        <th>Destination</th>
                        <th>Travel Start Date</th>
                        <th>Travel End Date</th>
                        <th>Plan/Description</th>
                        <th>Join?</th>
                    </thead>
                    <tbody>
                        {% for item in allTravels %}
                        <tr>
                            {% for itemB in users %}
                                {% if item.plannedby_user_id == itemB.id %}
                                    <td>{{itemB.first_name}} {{itemB.last_name}}</td>
                                {% endif %}
                            {% endfor %}
                            <td><a href='{% url "travels:destinationView" id=item.id %}'>{{item.destination}}</td>
                            <td>{{item.start_date}}</td>
                            <td>{{item.end_date}}</td>
                            <td>{{item.description}}</td>
                            <td><a href='{% url "travels:tripJoin" id=item.id %}'>Join</a>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </fieldset>
        </div>
    </div>
</body>
</html>

main/apps/travels/templates/travels/view.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>View Trip</title>
    <link rel='stylesheet' href=''>
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
    <script>
        $(document).ready(function() {
        });
    </script>
</head>
<body>
    <div class='main'>
        <a href='{% url "travels:travelsIndex" %}'>Home</a>
        <a href='{% url "login:signOut" %}'>Logout</a>
        <fieldset>
            <legend><h1>{{currentTravel.destination}}</h1></legend>
            <p>Planned By:  {{planner.first_name}} {{planner.last_name}}</p>
            <p>Description:  {{currentTravel.description}}</p>
            <p>Travel Date Start: {{currentTravel.start_date}}</p>
            <p>Travel End Date: {{currentTravel.end_date}}</p>
            <hr>
            <h4>Others Joining:</h4>
            {% for item in joiningUsers %}
                <p>{{item.first_name}} {{item.last_name}}</p>
            {% endfor %}
        </fieldset>
    </div>    
</body>
</html>